version: "3.9"

services:
  lus-api:
    build: .
    container_name: lus-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /usr/local/etc/xray/config.json:/usr/local/etc/xray/config.json
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn app:app --host 0.0.0.0 --port 8001