version: "3.9"

services:
  lus-api:
    build: .
    container_name: lus-api
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - /usr/local/etc/xray/config.json:/usr/local/etc/xray/config.json
    networks:
      - vless-network

networks:
  vless-network:
    external: true
    name: vless-networkcs  # <-- IL MANQUAIT ÇA ICI !